"use client";
import { useEffect, useMemo, useState } from "react";
import { AppShell } from "@/components/AppShell";

type Job = any;
export default function ProductionPage(){
  const [jobs,setJobs]=useState<Job[]>([]); const [assets,setAssets]=useState<any[]>([]); const [mode,setMode]=useState("demo"); const [busy,setBusy]=useState<string|null>(null); const [msg,setMsg]=useState("");
  async function load(){ const r=await fetch("/api/production/jobs?productId=PF-COOKIE-BRK"); const j=await r.json(); setJobs(j.jobs||[]);setAssets(j.canonicalAssets||[]);setMode(j.mode||"demo"); }
  useEffect(()=>{load()},[]);
  const assetTypes=useMemo(()=>new Set(assets.filter(x=>x.is_canonical).map(x=>x.asset_type)),[assets]);
  const missing=["front_pack","cookie_reference"].filter(x=>!assetTypes.has(x));
  async function render(jobId:string){ setBusy(jobId);setMsg(""); const r=await fetch("/api/production/render",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({jobId,brandId:"PF",productId:"PF-COOKIE-BRK"})}); const j=await r.json(); setMsg(r.ok?`Rendered ${jobId}`:(j.blocker||j.error||"Render failed")); await load(); setBusy(null); }
  return <AppShell active="production">
    <div className="topbar"><div><div className="eyebrow">Module 6</div><h1>Image Production</h1><p className="sub">Generate environment → composite canonical product → typeset approved copy → store final 1080×1350 creative.</p></div><span className={`badge ${mode==="live"?"ready":"draft"}`}>{mode.toUpperCase()}</span></div>
    {missing.length>0&&<div className="alert danger"><b>Source asset gate:</b> upload canonical {missing.join(" + ")} before rendering.</div>}
    {msg&&<div className="alert">{msg}</div>}
    <div className="grid2">
      <div className="card"><h2>Production controls</h2><p className="muted">The renderer will never ask the image model to create the Pur’ Ferme pack or exact cookie. Those layers come only from canonical uploads.</p><div className="gateStrip"><span>AI environment</span><span>Real pack</span><span>Real cookie</span><span>Exact typesetting</span><span>1080×1350 export</span></div></div>
      <div className="card"><h2>Canonical assets</h2><div className="assetMini">{["front_pack","cookie_reference","back_pack"].map(t=><div key={t} className="metric"><span>{t.replaceAll("_"," ")}</span><b>{assetTypes.has(t)?"✓ Verified":"Missing"}</b></div>)}</div></div>
    </div>
    <div className="card"><div className="sectionHead"><div><h2>Production jobs</h2><div className="muted">Jobs generated by Module 6.</div></div></div>
      <div className="jobList">{jobs.length===0?<div className="empty">No persistent production jobs yet. Run/seed Module 6 first.</div>:jobs.map(j=><div className="jobCard" key={j.id}><div><div className="eyebrow">{j.id} · {j.version}</div><h3>{j.briefs?.exact_hook || j.brief_id}</h3><p className="muted">{j.environment_prompt?.slice(0,260)}{j.environment_prompt?.length>260?"…":""}</p><div className="gateStrip"><span>{j.status}</span><span>Pack {j.briefs?.product_scale||30}%</span><span>{j.briefs?.format||"1080×1350"}</span></div></div><button className="btn btnPrimary" disabled={busy!==null||missing.length>0||j.status==="rendering"} onClick={()=>render(j.id)}>{busy===j.id?"Rendering…":j.status==="rendered"?"Render again":"Generate creative"}</button></div>)}</div>
    </div>
  </AppShell>
}
