"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { AppShell } from "@/components/AppShell";

type Product={id:string;brand_id:string;name:string;sku?:string|null;mrp?:number|null;selling_price?:number|null;pack_size?:string|null;product_truth:any;claims_allowed:any;claims_prohibited:any;status:string};
const blank:Product={id:"",brand_id:"PF",name:"",sku:"",mrp:null,selling_price:null,pack_size:"",status:"draft",product_truth:{category:"",description:"",ingredients:[],facts:[],usage:[]},claims_allowed:[],claims_prohibited:[]};
const lines=(v:any)=>Array.isArray(v)?v.join("\n"):"";
const list=(v:FormDataEntryValue|null)=>String(v||"").split("\n").map(x=>x.trim()).filter(Boolean);

export default function ProductsPage(){
  const [products,setProducts]=useState<Product[]>([]); const [selected,setSelected]=useState<Product|null>(null); const [creating,setCreating]=useState(false); const [busy,setBusy]=useState(false); const [msg,setMsg]=useState("");
  async function load(){const r=await fetch("/api/products?brand=PF");const j=await r.json();if(r.ok){setProducts(j); if(selected){const fresh=j.find((p:Product)=>p.id===selected.id); if(fresh)setSelected(fresh);}}else setMsg(j.error||"Could not load products.")}
  useEffect(()=>{load()},[]);
  const activeCount=useMemo(()=>products.filter(p=>p.status==="active").length,[products]);
  function startNew(){setCreating(true);setSelected({...blank,product_truth:{...blank.product_truth}});setMsg("")}
  function edit(p:Product){setCreating(false);setSelected(p);setMsg("")}
  async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMsg("");const fd=new FormData(e.currentTarget);const truth={...(selected?.product_truth||{}),category:String(fd.get("category")||""),description:String(fd.get("description")||""),ingredients:list(fd.get("ingredients")),facts:list(fd.get("facts")),usage:list(fd.get("usage"))};const payload={id:fd.get("id"),brand_id:"PF",name:fd.get("name"),sku:fd.get("sku"),mrp:fd.get("mrp"),selling_price:fd.get("selling_price"),pack_size:fd.get("pack_size"),status:fd.get("status"),product_truth:truth,claims_allowed:list(fd.get("claims_allowed")),claims_prohibited:list(fd.get("claims_prohibited"))};const url=creating?"/api/products":`/api/products/${encodeURIComponent(String(selected?.id))}`;const r=await fetch(url,{method:creating?"POST":"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const j=await r.json();if(r.ok){setMsg(creating?"Product added to catalog.":"Product updated.");setSelected(j);setCreating(false);await load()}else setMsg(j.error||"Save failed");setBusy(false)}
  async function remove(){if(!selected||creating)return; if(!confirm(`Delete ${selected.name}? Use Archive if it already has history.`))return;const r=await fetch(`/api/products/${encodeURIComponent(selected.id)}`,{method:"DELETE"});const j=await r.json();if(r.ok){setMsg("Product deleted.");setSelected(null);await load()}else setMsg(j.error||"Delete failed")}
  return <AppShell active="products"><div className="topbar"><div><div className="eyebrow">Catalog</div><h1>Products</h1><p className="sub">All Pur’ Ferme products live here. Active products can enter the creative pipeline; planned/draft products can be completed before launch.</p></div><div className="heroActions"><span className="badge ready">{activeCount} ACTIVE</span><button className="btn btnPrimary" onClick={startNew}>+ Add product</button></div></div>
  {msg&&<div className={`alert ${msg.includes("added")||msg.includes("updated")||msg.includes("deleted")?"ok":"warn"}`} style={{marginBottom:16}}>{msg}</div>}
  <section className="catalogGrid">{products.map(p=>{const t=p.product_truth||{};return <button key={p.id} className={`productCard ${selected?.id===p.id?"selected":""}`} onClick={()=>edit(p)}><div className="productCardTop"><span className="eyebrow">{p.id}</span><span className={`badge ${p.status==="active"?"ready":p.status==="planned"?"review":"draft"}`}>{p.status.toUpperCase()}</span></div><h3>{p.name}</h3><p className="muted small">{t.category||"Category not set"} · {p.pack_size||"Pack size pending"}</p><div className="productMeta"><span>{p.mrp!=null?`MRP ₹${p.mrp}`:"MRP pending"}</span><span>{p.sku||"SKU pending"}</span></div></button>})}</section>
  {!products.length&&<div className="empty">No products found. Run the V6 catalog upgrade SQL or add your first product.</div>}
  {selected&&<section className="card wideCard editorCard"><div className="sectionHead"><div><div className="eyebrow">{creating?"New product":"Edit product"}</div><h2>{creating?"Add to catalog":selected.name}</h2></div>{!creating&&<button className="btn btnGhost dangerText" onClick={remove}>Delete</button>}</div><form onSubmit={save}><div className="formGrid"><label>Product ID<input name="id" defaultValue={selected.id} disabled={!creating} required placeholder="PF-PRODUCT-ID"/></label><label>Status<select name="status" defaultValue={selected.status}><option value="active">Active</option><option value="planned">Planned</option><option value="draft">Draft</option><option value="inactive">Inactive</option><option value="archived">Archived</option></select></label><label>Product name<input name="name" defaultValue={selected.name} required/></label><label>Category<input name="category" defaultValue={selected.product_truth?.category||""} placeholder="Cookies / Nut butter / Porridge"/></label><label>SKU<input name="sku" defaultValue={selected.sku||""}/></label><label>Pack size<input name="pack_size" defaultValue={selected.pack_size||""} placeholder="240 g"/></label><label>MRP ₹<input name="mrp" type="number" step="0.01" min="0" defaultValue={selected.mrp??""}/></label><label>Selling price ₹<input name="selling_price" type="number" step="0.01" min="0" defaultValue={selected.selling_price??""}/></label></div><label>Description<textarea name="description" defaultValue={selected.product_truth?.description||""}/></label><div className="formGrid"><label>Ingredients <span className="muted small">One per line</span><textarea name="ingredients" defaultValue={lines(selected.product_truth?.ingredients)}/></label><label>Verified facts / features <span className="muted small">One per line</span><textarea name="facts" defaultValue={lines(selected.product_truth?.facts)}/></label><label>Usage occasions <span className="muted small">One per line</span><textarea name="usage" defaultValue={lines(selected.product_truth?.usage)}/></label><label>Allowed claims <span className="muted small">One per line</span><textarea name="claims_allowed" defaultValue={lines(selected.claims_allowed)}/></label></div><label>Prohibited / unverified claims <span className="muted small">One per line</span><textarea name="claims_prohibited" defaultValue={lines(selected.claims_prohibited)}/></label><div className="heroActions"><button className="btn btnPrimary" disabled={busy}>{busy?"Saving…":creating?"Add product":"Save product"}</button><button type="button" className="btn btnGhost" onClick={()=>setSelected(null)}>Close</button></div></form></section>}
  </AppShell>
}
