"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { AppShell } from "@/components/AppShell";

type Asset={id:string;asset_type:string;is_canonical:boolean;storage_path:string;source?:string;product_id?:string};
type Product={id:string;name:string;status:string;pack_size?:string|null};

export default function AssetsPage(){
  const [assets,setAssets]=useState<Asset[]>([]); const [products,setProducts]=useState<Product[]>([]); const [productId,setProductId]=useState("PF-COOKIE-BRK"); const [msg,setMsg]=useState(""); const [busy,setBusy]=useState(false);
  async function loadProducts(){const r=await fetch("/api/products?brand=PF");const j=await r.json();if(r.ok){setProducts(j);if(j.length&&!j.some((p:Product)=>p.id===productId))setProductId(j[0].id)}}
  async function loadAssets(id=productId){const r=await fetch(`/api/workspace?brand=PF&product=${encodeURIComponent(id)}`);const j=await r.json();if(r.ok)setAssets(j.assets||[]);else setMsg(j.error||"Could not load assets.")}
  useEffect(()=>{loadProducts()},[]); useEffect(()=>{if(productId)loadAssets(productId)},[productId]);
  const product=useMemo(()=>products.find(p=>p.id===productId),[products,productId]);
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMsg("");const fd=new FormData(e.currentTarget);fd.set("brandId","PF");fd.set("productId",productId);const r=await fetch("/api/assets/upload",{method:"POST",body:fd});const j=await r.json();if(!r.ok)setMsg(j.error||"Upload failed");else{setMsg("Asset uploaded and registered.");(e.target as HTMLFormElement).reset();await loadAssets()}setBusy(false)}
  async function setCanonical(a:Asset){const r=await fetch(`/api/assets/${a.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({is_canonical:!a.is_canonical})});const j=await r.json();if(r.ok){setMsg(j.is_canonical?"Canonical source updated.":"Canonical flag removed.");await loadAssets()}else setMsg(j.error||"Update failed")}
  async function remove(a:Asset){if(!confirm("Delete this asset from the registry and local storage?"))return;const r=await fetch(`/api/assets/${a.id}`,{method:"DELETE"});const j=await r.json();if(r.ok){setMsg("Asset deleted.");await loadAssets()}else setMsg(j.error||"Delete failed")}
  const has=(type:string)=>assets.some(a=>a.is_canonical&&a.asset_type===type);
  return <AppShell active="assets"><div className="topbar"><div><div className="eyebrow">Product source-of-truth</div><h1>Asset Library</h1><p className="sub">Manage canonical packshots and real product references per product. The production engine will refuse to invent missing product assets.</p></div><span className="badge ready">LOCAL STORAGE</span></div>
  {msg&&<div className={`alert ${msg.includes("uploaded")||msg.includes("updated")||msg.includes("deleted")?"ok":"warn"}`} style={{marginBottom:16}}>{msg}</div>}
  <section className="card productPicker"><label>Product<select value={productId} onChange={e=>setProductId(e.target.value)}>{products.map(p=><option key={p.id} value={p.id}>{p.name} · {p.id}</option>)}</select></label><div><div className="eyebrow">Selected</div><strong>{product?.name||productId}</strong><div className="muted small">{product?.status?.toUpperCase()} {product?.pack_size?`· ${product.pack_size}`:""}</div></div></section>
  <section className="grid grid2"><form className="card" onSubmit={submit}><h2>Upload product asset</h2><label>Asset type<select name="assetType" defaultValue="front_pack"><option value="front_pack">Front pack</option><option value="back_pack">Back pack</option><option value="cookie_reference">Real cookie / product reference</option><option value="ingredient_reference">Ingredient reference</option><option value="logo">Logo</option><option value="other">Other</option></select></label><label>File<input name="file" type="file" accept="image/*,.pdf" required/></label><label className="rowCheck"><input type="checkbox" name="canonical" value="true" defaultChecked/> Mark as canonical source-of-truth</label><button className="btn btnPrimary" disabled={busy}>{busy?"Uploading…":"Upload asset"}</button><p className="muted small">Files are stored inside the app’s local <span className="mono">storage/</span> folder and registered in PostgreSQL.</p></form>
  <div className="card"><h2>Production gate</h2><div className="gateItem"><span>Front pack</span><b className={has("front_pack")?"goodText":"dangerText"}>{has("front_pack")?"VERIFIED":"MISSING"}</b></div><div className="gateItem"><span>Real product reference</span><b className={has("cookie_reference")?"goodText":"dangerText"}>{has("cookie_reference")?"VERIFIED":"MISSING"}</b></div><div className="gateItem"><span>Back pack</span><b>{has("back_pack")?"VERIFIED":"OPTIONAL / MISSING"}</b></div><p className="muted small">For cookies, “Real product reference” means a true cookie photograph. For peanut butter, porridge, bars or nutrition mixes, upload the real consumable/product reference appropriate to that SKU.</p></div></section>
  <section className="section"><div className="sectionHead"><div><h2>Registered assets</h2><div className="muted">Only canonical assets define how the real product is allowed to appear.</div></div></div><div className="tableWrap"><table><thead><tr><th>Type</th><th>Canonical</th><th>Source</th><th>Storage path</th><th>Actions</th></tr></thead><tbody>{assets.length?assets.map(a=><tr key={a.id}><td>{a.asset_type}</td><td><span className={`badge ${a.is_canonical?"ready":"draft"}`}>{a.is_canonical?"YES":"NO"}</span></td><td>{a.source||"—"}</td><td className="mono">{a.storage_path}</td><td><div className="rowActions"><button className="btn btnGhost btnSmall" onClick={()=>setCanonical(a)}>{a.is_canonical?"Unset canonical":"Make canonical"}</button><button className="btn btnGhost btnSmall dangerText" onClick={()=>remove(a)}>Delete</button></div></td></tr>):<tr><td colSpan={5} className="muted">No assets registered for this product yet.</td></tr>}</tbody></table></div></section></AppShell>
}
